### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [odd-industries/lemu-qgis-plugins#1]
Please fix https://le.mu/ in metadata.txt , we need a link that references the plugin usage

**Comment by NyakudyaA** [comment]
ping @aleksiGit

**Comment by aleksiGit** [comment]
> Please fix https://le.mu/ in metadata.txt , we need a link that references the plugin usage

@NyakudyaA  Thank you for bringing it to my attention. I have already fixed the issue in metadata.txt. The link to https://le.mu/ now correctly references the plugin usage. Please let me know if there's anything else I can help with.
